apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lulan.fullname" . }}
  labels: {{- include "lulan.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "lulan.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "lulan.labels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: LULAN_LISTEN_ADDR
              value: 0.0.0.0:8080
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "lulan.secretName" . }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 15
          resources: {{- toYaml .Values.resources | nindent 12 }}
