apiVersion: v1
kind: Service
metadata:
  name: {{ include "lulan.fullname" . }}
  labels: {{- include "lulan.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector: {{- include "lulan.labels" . | nindent 4 }}
